# permissions for end users to view cexencryptvols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cex-encrypt-vol
    app.kubernetes.io/managed-by: kustomize
  name: cexencryptvol-viewer-role
rules:
- apiGroups:
  - cex.ibmz.com
  resources:
  - cexencryptvols
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cex.ibmz.com
  resources:
  - cexencryptvols/status
  verbs:
  - get
